package gui;

import database.DatabaseManager;
import java.util.ArrayList;
import repository.Species;

/**
 *
 * @author hamza
 */

public class MainScreen extends javax.swing.JPanel {

    /**
     * Creates new form MainScreen
     */
    public MainScreen() {
        initComponents();
    }
    
    public void updateDailyTasks()
    {
        // Getting access to Database
        DatabaseManager db = DatabaseManager.getInstance();
        
        // getting species stored 
        ArrayList<Species> species = db.getFeedingTimes();
        
        String dailyTasks = "Daily Tasks: ";
        if(species != null)
        {
            for(int i = 0; i < species.size(); i++)
            {
                if(species.get(i).getType() == 0) // It's an animal
                {
                    dailyTasks = dailyTasks + "\n Feed animal " + species.get(i).getName() + " with ID " 
                                            + species.get(i).getsID() + " at time " + species.get(i).getFeedingTime();                
                }
                if(species.get(i).getType() == 1) // It's a plant
                {
                    dailyTasks = dailyTasks + "\n Water plant " + species.get(i).getName() + " with ID " 
                                            + species.get(i).getsID() + " at time " + species.get(i).getFeedingTime();
                }
            }
        }
        
        dailyTasksL.setText(dailyTasks);
        System.out.println("daily tasks: " + dailyTasks);
    }
   
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dailyTasks = new javax.swing.JPanel();
        dailyTasksL = new javax.swing.JLabel();
        calendarPanel1 = new com.github.lgooddatepicker.components.CalendarPanel();

        dailyTasksL.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        dailyTasksL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dailyTasksLMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout dailyTasksLayout = new javax.swing.GroupLayout(dailyTasks);
        dailyTasks.setLayout(dailyTasksLayout);
        dailyTasksLayout.setHorizontalGroup(
            dailyTasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dailyTasksLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dailyTasksL, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                .addContainerGap())
        );
        dailyTasksLayout.setVerticalGroup(
            dailyTasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dailyTasksLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dailyTasksL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        calendarPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                calendarPanel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dailyTasks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(calendarPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dailyTasks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(calendarPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void calendarPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calendarPanel1MouseClicked
        updateDailyTasks();      
        
    }//GEN-LAST:event_calendarPanel1MouseClicked

    private void dailyTasksLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dailyTasksLMouseClicked
        updateDailyTasks();
    }//GEN-LAST:event_dailyTasksLMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.github.lgooddatepicker.components.CalendarPanel calendarPanel1;
    private javax.swing.JPanel dailyTasks;
    private javax.swing.JLabel dailyTasksL;
    // End of variables declaration//GEN-END:variables
}
