/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import security.PasswordManager;

/**
 *
 * @author hamza
 */
public class PasswordScreen extends javax.swing.JPanel {

    /**
     * Creates new form PasswordScreen
     */
    boolean passCheck;
    
    public PasswordScreen() {
        passCheck = false;
        initComponents();
    }
    
    public boolean getPassCheck()
    {
        return passCheck;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcomeL = new javax.swing.JLabel();
        enterPassL = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        confirmB = new javax.swing.JButton();
        msgL = new javax.swing.JLabel();

        welcomeL.setText("Welcome to Zoo-Master");

        enterPassL.setText("Please Enter Your Password:");

        confirmB.setText("Confirm");
        confirmB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(183, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(msgL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(passwordField)
                    .addComponent(enterPassL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(confirmB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(welcomeL)))
                .addGap(181, 181, 181))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(welcomeL)
                .addGap(18, 18, 18)
                .addComponent(enterPassL)
                .addGap(18, 18, 18)
                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(confirmB)
                .addGap(18, 18, 18)
                .addComponent(msgL)
                .addContainerGap(96, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void confirmBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmBActionPerformed
        PasswordManager pm = PasswordManager.getInstance();
	passCheck = pm.isCorrect(new String(passwordField.getPassword()));
        if (passCheck == false)
        {
            msgL.setText("Your Password Is Incorrect!");
        }
        else
        {
            msgL.setText("Your Password Is Correct!");
        }
    }//GEN-LAST:event_confirmBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confirmB;
    private javax.swing.JLabel enterPassL;
    private javax.swing.JLabel msgL;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel welcomeL;
    // End of variables declaration//GEN-END:variables
}
