/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author hamza
 */
public class PlantAddScreen extends javax.swing.JPanel {

    /**
     * Creates new form PlantAddScreen
     */
    public PlantAddScreen() {
        initComponents();
    }
    
    public void clear()
    {
        genderBG.clearSelection();
    }
    
    public String getWateringTime()
    {
       return wateringTimeTP.getTimeStringOrEmptyString();
    }
    
    public String getGender()
    {
        if(femaleRB.isSelected())
        {
            return "Female";
        }
        if(maleRB.isSelected())
        {
            return "Male";
        }
        
        return "NA";
    }
    
    public String getLightTimeStart()
    {
        return lightTimeStartTP.getTimeStringOrEmptyString();
    }
    
    public String getLightTimeEnd()
    {
        return lightTimeEndTP.getTimeStringOrEmptyString();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderBG = new javax.swing.ButtonGroup();
        wateringTimeL = new javax.swing.JLabel();
        genderL = new javax.swing.JLabel();
        wateringTimeTP = new com.github.lgooddatepicker.components.TimePicker();
        lightTimeStartL = new javax.swing.JLabel();
        lightTimeStartTP = new com.github.lgooddatepicker.components.TimePicker();
        lightTimeEndL = new javax.swing.JLabel();
        lightTimeEndTP = new com.github.lgooddatepicker.components.TimePicker();
        maleRB = new javax.swing.JRadioButton();
        femaleRB = new javax.swing.JRadioButton();

        setPreferredSize(new java.awt.Dimension(400, 150));

        wateringTimeL.setText("Watering Time:");

        genderL.setText("Gender:");

        lightTimeStartL.setText("Light Time Start:");

        lightTimeEndL.setText("Light Time End:");

        genderBG.add(maleRB);
        maleRB.setText("Male");

        genderBG.add(femaleRB);
        femaleRB.setText("Female");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(wateringTimeL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(wateringTimeTP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lightTimeStartL)
                            .addComponent(genderL))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lightTimeStartTP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(maleRB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(femaleRB))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lightTimeEndL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lightTimeEndTP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(209, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wateringTimeL)
                    .addComponent(wateringTimeTP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genderL)
                    .addComponent(maleRB)
                    .addComponent(femaleRB))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lightTimeStartL)
                    .addComponent(lightTimeStartTP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lightTimeEndL)
                    .addComponent(lightTimeEndTP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton femaleRB;
    private javax.swing.ButtonGroup genderBG;
    private javax.swing.JLabel genderL;
    private javax.swing.JLabel lightTimeEndL;
    private com.github.lgooddatepicker.components.TimePicker lightTimeEndTP;
    private javax.swing.JLabel lightTimeStartL;
    private com.github.lgooddatepicker.components.TimePicker lightTimeStartTP;
    private javax.swing.JRadioButton maleRB;
    private javax.swing.JLabel wateringTimeL;
    private com.github.lgooddatepicker.components.TimePicker wateringTimeTP;
    // End of variables declaration//GEN-END:variables
}
